import streamlit as st
import datetime
import pandas as pd
import plotly.express as px
import database
import io
from fpdf import FPDF

# Custom PDF Report Class using fpdf2
class LeaveReportPDF(FPDF):
    def header(self):
        # Logo banner placeholder styling or elegant typography
        self.set_text_color(30, 58, 138)  # Deep Navy blue
        self.set_font('helvetica', 'B', 16)
        self.cell(0, 10, 'Leave Management System - Executive Summary', border=False, ln=True, align='C')
        
        self.set_text_color(100, 116, 139)  # Slate grey
        self.set_font('helvetica', 'I', 10)
        self.cell(0, 5, f'Generated on: {datetime.datetime.now().strftime("%b %d, %Y %I:%M %p")}', border=False, ln=True, align='C')
        self.ln(8)
        
        # Draw a stylish header divider line
        self.set_draw_color(226, 232, 240)
        self.line(10, 30, 200, 30)
        self.ln(5)
        
    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        self.set_text_color(148, 163, 184)
        self.set_font('helvetica', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}} - Confidentially Generated by HR Agent AI', align='C')

def generate_pdf_report(requests_data):
    pdf = LeaveReportPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    
    pdf.set_text_color(30, 58, 138)
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 8, 'All Submitted Leave Applications', ln=True)
    pdf.ln(2)
    
    # Table Header
    pdf.set_text_color(255, 255, 255)
    pdf.set_fill_color(30, 58, 138)  # Navy
    pdf.set_font('helvetica', 'B', 9)
    
    # Define widths: Employee (45), Type (20), Dates (45), Days (12), Status (23), AI Recommendation (45)
    pdf.cell(45, 8, 'Employee', border=1, fill=True, align='C')
    pdf.cell(20, 8, 'Type', border=1, fill=True, align='C')
    pdf.cell(45, 8, 'Dates', border=1, fill=True, align='C')
    pdf.cell(12, 8, 'Days', border=1, fill=True, align='C')
    pdf.cell(23, 8, 'Status', border=1, fill=True, align='C')
    pdf.cell(45, 8, 'AI Assessment', border=1, fill=True, align='C', ln=True)
    
    # Table Body
    pdf.set_text_color(51, 65, 85)  # Dark charcoal text
    pdf.set_font('helvetica', '', 8.5)
    
    toggle_color = True
    for req in requests_data:
        # Toggle background row shading for readability
        if toggle_color:
            pdf.set_fill_color(248, 250, 252)  # Very light grey
        else:
            pdf.set_fill_color(255, 255, 255)
            
        toggle_color = not toggle_color
        
        s_date = req['start_date']
        e_date = req['end_date']
        days = (datetime.datetime.strptime(e_date, "%Y-%m-%d") - datetime.datetime.strptime(s_date, "%Y-%m-%d")).days + 1
        
        # Status Color formatting in PDF
        status_txt = req['status']
        ai_rec_txt = f"{req['ai_recommendation']} ({req['ai_reason'][:30]}...)" if req['ai_reason'] else req['ai_recommendation']
        
        pdf.cell(45, 7, str(req['employee_name'])[:22], border=1, fill=True)
        pdf.cell(20, 7, str(req['leave_type']), border=1, fill=True, align='C')
        pdf.cell(45, 7, f"{s_date} to {e_date}", border=1, fill=True, align='C')
        pdf.cell(12, 7, str(days), border=1, fill=True, align='C')
        pdf.cell(23, 7, status_txt, border=1, fill=True, align='C')
        pdf.cell(45, 7, ai_rec_txt[:25], border=1, fill=True, ln=True)
        
    return pdf.output()

def show_admin_dashboard(user):

    # ── Global CSS: Back button + admin metric cards ──
    st.markdown("""
    <style>
    .admin-back-btn button {
        background: linear-gradient(135deg, #2563eb 0%, #7c3aed 100%) !important;
        color: #ffffff !important;
        border: none !important;
        border-radius: 14px !important;
        font-size: 15px !important;
        font-weight: 700 !important;
        box-shadow: 0 4px 18px rgba(37,99,235,0.25) !important;
        padding: 10px 22px !important;
        transition: all 0.22s ease !important;
        width: auto !important;
    }
    .admin-back-btn button:hover {
        transform: translateX(-3px) scale(1.03) !important;
        box-shadow: 0 8px 28px rgba(37,99,235,0.38) !important;
    }
    .admin-cards-row {
        display: flex;
        flex-direction: row;
        gap: 20px;
        margin: 16px 0 28px 0;
        flex-wrap: nowrap;
    }
    .admin-card {
        flex: 1;
        border-radius: 22px;
        padding: 28px 24px 24px 24px;
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        box-shadow: 0 8px 32px rgba(0,0,0,0.13);
        transition: transform 0.22s ease, box-shadow 0.22s ease;
        min-width: 0;
        position: relative;
        overflow: hidden;
        color: #fff;
    }
    .admin-card:hover {
        transform: translateY(-5px);
        box-shadow: 0 18px 48px rgba(0,0,0,0.18);
    }
    .admin-card.pending  { background: linear-gradient(135deg, #f59e0b 0%, #ef4444 100%); }
    .admin-card.approved { background: linear-gradient(135deg, #16a34a 0%, #84cc16 100%); }
    .admin-card.rejected { background: linear-gradient(135deg, #dc2626 0%, #f97316 100%); }
    .admin-card.total    { background: linear-gradient(135deg, #7c3aed 0%, #ec4899 100%); }
    .admin-card-blob {
        position: absolute;
        width: 130px; height: 130px;
        border-radius: 50%;
        background: rgba(255,255,255,0.10);
        bottom: -30px; right: -30px;
        pointer-events: none;
    }
    .admin-card-icon  { font-size: 2.2rem; margin-bottom: 12px; filter: drop-shadow(0 2px 6px rgba(0,0,0,0.18)); }
    .admin-card-label { font-size: 0.82rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; opacity: 0.88; margin-bottom: 6px; }
    .admin-card-number{ font-size: 3.4rem; font-weight: 900; line-height: 1; margin-bottom: 4px; letter-spacing: -0.03em; }
    .admin-card-footer{ font-size: 0.88rem; opacity: 0.82; font-weight: 500; }
    </style>
    """, unsafe_allow_html=True)

    # ── Top bar: Back button (left) + Title (right) ──
    col_back, col_title = st.columns([1, 6])
    with col_back:
        st.markdown('<div class="admin-back-btn">', unsafe_allow_html=True)
        if st.button("← Back", key="admin_back_btn"):
            st.session_state.update({'page': 'home', 'logged_in': False, 'user': None, 'role': None})
            st.rerun()
        st.markdown('</div>', unsafe_allow_html=True)
    with col_title:
        st.markdown(
            f"<h1 style='font-size:2.2rem; font-weight:800; color:#1e3a8a; margin:0; padding-top:6px;'>"
            f"Admin Control Center &nbsp;"
            f"<span style='font-size:1.1rem; color:#7c3aed; font-weight:500;'>Welcome, {user['name']}! 🛡️</span>"
            f"</h1>",
            unsafe_allow_html=True
        )

    # Fetch data
    requests = database.get_all_leave_requests()

    # ── Metric Cards (colorful, one row) ──
    pending_count  = sum(1 for r in requests if r['status'] == 'Pending')
    approved_count = sum(1 for r in requests if r['status'] == 'Approved')
    rejected_count = sum(1 for r in requests if r['status'] == 'Rejected')
    total_count    = len(requests)

    st.markdown(f"""
    <div class="admin-cards-row">
        <div class="admin-card pending">
            <div class="admin-card-blob"></div>
            <div class="admin-card-icon">⏳</div>
            <div class="admin-card-label">Pending Review</div>
            <div class="admin-card-number">{pending_count}</div>
            <div class="admin-card-footer">needs attention</div>
        </div>
        <div class="admin-card approved">
            <div class="admin-card-blob"></div>
            <div class="admin-card-icon">✅</div>
            <div class="admin-card-label">Approved</div>
            <div class="admin-card-number">{approved_count}</div>
            <div class="admin-card-footer">approved requests</div>
        </div>
        <div class="admin-card rejected">
            <div class="admin-card-blob"></div>
            <div class="admin-card-icon">❌</div>
            <div class="admin-card-label">Rejected</div>
            <div class="admin-card-number">{rejected_count}</div>
            <div class="admin-card-footer">rejected requests</div>
        </div>
        <div class="admin-card total">
            <div class="admin-card-blob"></div>
            <div class="admin-card-icon">📋</div>
            <div class="admin-card-label">Total Applications</div>
            <div class="admin-card-number">{total_count}</div>
            <div class="admin-card-footer">all requests</div>
        </div>
    </div>
    """, unsafe_allow_html=True)

    st.markdown("<hr>", unsafe_allow_html=True)


    # Main Tabs
    tab_review, tab_analytics, tab_audit = st.tabs([
        "📥 Pending Requests", 
        "📈 Leave Analytics",
        "🛡️ System Audit Logs"
    ])
    
    # ---------------- TAB 1: PENDING REQUESTS ----------------
    with tab_review:
        st.subheader("Applications Awaiting Decision")
        pending_requests = [r for r in requests if r['status'] == 'Pending']
        
        if not pending_requests:
            st.success("✅ Clean slate! No pending leave applications to review.")
        else:
            for req in pending_requests:
                duration = (datetime.datetime.strptime(req['end_date'], "%Y-%m-%d") - datetime.datetime.strptime(req['start_date'], "%Y-%m-%d")).days + 1
                
                # Setup custom panel styling for pending requests
                rec = req['ai_recommendation']
                rec_color = "#16a34a" if rec == 'Approve' else ("#d97706" if rec == 'Escalate' else "#dc2626")
                
                st.markdown(f"""
                <div class="review-panel-container">
                    <div style="display:flex; justify-content:space-between; align-items:center;">
                        <span style="font-size:18px; font-weight:bold; color:#1e293b;">{req['employee_name']} (@{req['employee_username']})</span>
                        <span class="status-badge status-pending" style="font-size:12px;">PENDING</span>
                    </div>
                    <div style="margin-top: 10px; font-size:14px; color:#475569;">
                        <p><strong>Leave Details:</strong> {req['leave_type']} Leave for <strong>{duration} Day(s)</strong> ({req['start_date']} to {req['end_date']})</p>
                        <p><strong>Reason:</strong> "{req['reason']}"</p>
                        <p><strong>Balances:</strong> Casual: {req['casual_balance']}d | Sick: {req['sick_balance']}d | Paid: {req['paid_balance']}d</p>
                    </div>
                    
                    <div class="ai-box" style="border-left: 4px solid {rec_color}; background-color: rgba(248, 250, 252, 0.9);">
                        <h5 style="margin: 0; color: #1e3a8a; font-size:14px;"><span class="ai-sparkle">✨</span> AI Agent Assessment</h5>
                        <p style="margin: 5px 0 0 0; font-size:13.5px;">
                            <strong>AI Recommendation:</strong> <span style="color: {rec_color}; font-weight: bold;">{rec}</span>
                        </p>
                        <p style="margin: 3px 0 0 0; font-size:12.5px; color:#475569;"><em>"{req['ai_reason']}"</em></p>
                    </div>
                </div>
                """, unsafe_allow_html=True)
                
                col1, col2, _ = st.columns([1, 1, 4])
                
                # Approve/Reject logic
                with col1:
                    if st.button("Approve", key=f"app_{req['id']}", use_container_width=True):
                        success, msg = database.update_leave_status(req['id'], 'Approved', user['id'], user['username'])
                        if success:
                            st.success("Request approved!")
                            st.rerun()
                        else:
                            st.error(f"Failed to approve: {msg}")
                with col2:
                    if st.button("Reject", key=f"rej_{req['id']}", use_container_width=True):
                        success, msg = database.update_leave_status(req['id'], 'Rejected', user['id'], user['username'])
                        if success:
                            st.info("Request rejected.")
                            st.rerun()
                        else:
                            st.error(f"Failed to reject: {msg}")
                
                st.markdown("<hr style='border: 0.5px dashed #ccc; margin: 20px 0;'>", unsafe_allow_html=True)

    # ---------------- TAB 2: ANALYTICS ----------------
    with tab_analytics:
        st.subheader("Data-Driven Insights")
        if not requests:
            st.info("No leave records available to chart.")
        else:
            # Prepare data
            df = pd.DataFrame([dict(r) for r in requests])
            
            col_chart1, col_chart2 = st.columns(2)
            
            with col_chart1:
                # 1. Leave Type Distribution (Pie Chart)
                type_counts = df['leave_type'].value_counts().reset_index()
                type_counts.columns = ['Leave Type', 'Count']
                fig_pie = px.pie(
                    type_counts, 
                    values='Count', 
                    names='Leave Type', 
                    title="Leave Request Types Distribution",
                    color_discrete_sequence=px.colors.qualitative.Pastel
                )
                fig_pie.update_layout(paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)")
                st.plotly_chart(fig_pie, use_container_width=True)
                
            with col_chart2:
                # 2. Status Distribution (Bar Chart)
                status_counts = df['status'].value_counts().reset_index()
                status_counts.columns = ['Status', 'Count']
                fig_bar = px.bar(
                    status_counts, 
                    x='Status', 
                    y='Count', 
                    title="Leave Applications Status",
                    color='Status',
                    color_discrete_map={'Pending': '#f59e0b', 'Approved': '#10b981', 'Rejected': '#ef4444'}
                )
                fig_bar.update_layout(paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)")
                st.plotly_chart(fig_bar, use_container_width=True)

    # ---------------- TAB 3: AUDIT LOGS ----------------
    with tab_audit:
        st.subheader("Admin Security Audit Log Trail")
        st.markdown("Cryptographic-like tracking of all status modifications and system balance changes.")
        
        logs = database.get_audit_logs()
        
        if not logs:
            st.info("System audit logs are currently empty. Log modifications will appear here.")
        else:
            # Styled timeline presentation
            for log in logs:
                log_time = datetime.datetime.fromisoformat(log['timestamp']).strftime("%b %d, %Y %I:%M %p")
                
                st.markdown(f"""
                <div class="audit-item">
                    <div style="display:flex; justify-content:space-between; font-size:13px; color:#475569;">
                        <span><strong>Admin Action:</strong> <span class="highlight-text">{log['action']}</span></span>
                        <span>{log_time}</span>
                    </div>
                    <div style="margin-top: 5px; font-size:13.5px; color:#1e293b;">
                        <strong>Performed By:</strong> {log['admin_name']} (@{log['admin_username']})<br>
                        <strong>Details:</strong> {log['details']}<br>
                        {f"<strong>Target Request ID:</strong> #{log['target_request_id']}" if log['target_request_id'] else ""}
                    </div>
                </div>
                """, unsafe_allow_html=True)
